export const ROLES_PERMISSIONS = {
  owner: [
    "create_department",
    "edit_department",
    "delete_department",
    "assign_roles",
    "revoke_roles",
    "add_members",
    "remove_members",
    "view_all_users",
    "approve_requests",
    "access_all_reports",
    "configure_settings",
    "transfer_ownership",
  ],
  manager: [
    "assign_roles_department",
    "add_members_department",
    "remove_members_department",
    "approve_leave_department",
    "view_reports_department",
    "assign_tasks",
    "view_team",
    "assign_tasks_to_team",
  ],
  hr: [
    "view_employee_details",
    "manage_payroll",
    "approve_leave",
    "onboard_employee",
    "offboard_employee",
    "view_all_departments",
    "edit_limited_profiles",
  ],
  projectManager: [
    "create_project",
    "assign_team_leads",
    "assign_project_tasks",
    "track_task_progress",
    "approve_task_completion",
    "view_project_reports",
  ],
  teamLead: [
    "assign_team_tasks",
    "view_team_progress",
    "provide_feedback",
    "request_new_members",
    "approve_task_submissions",
  ],
  employee: [
    "view_tasks",
    "submit_task_updates",
    "submit_leave_request",
    "view_project_info",
    "edit_own_profile",
  ],
};